### ISSUE TITLE
id with invalid querySelector character throw error on get labels

### ISSUE THREAD

**Issue by odeniel** [calebdwilliams/element-internals-polyfill#78]
I have an error with element with id like "ex.ample[0]" because of chars ".", "[", "]"...
The error throw on element-internals.ts >   get labels(): LabelsList
line:
`return hostRoot.querySelectorAll<HTMLLabelElement>(`[for=${id}]`) as unknown as LabelsList;`

This error is fixed using "" in selector like that:
`return hostRoot.querySelectorAll<HTMLLabelElement>(`[for="${id}"]`) as unknown as LabelsList;`

I think the fix coulb be correct but I'm not sure if it's correct to accept all types of selector.

error:

```
SyntaxError: '[for=CAB.LINE_list]' is not a valid selector

      66972 |         const hostRoot = ref.getRootNode();
      66973 |         if (hostRoot && id2) {
    > 66974 |           return hostRoot.querySelectorAll(`[for=${id2}]`);
            |                           ^
      66975 |         }
      66976 |         return [];
      66977 |       }

      at emit (node_modules/nwsapi/src/nwsapi.js:565:17)
      at Object._querySelectorAll [as select] (node_modules/nwsapi/src/nwsapi.js:1513:9)
      at DocumentImpl.querySelectorAll (node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:78:26)
      at Document.querySelectorAll (node_modules/jsdom/lib/jsdom/living/generated/Document.js:992:58)
      at ElementInternals.labels (dist/web-components.js:66974:27)
      at upgradeInternals (dist/web-components.js:66697:17)
      at new ElementInternals (dist/web-components.js:66934:9)
      at HTMLElement.attachInternals (dist/web-components.js:67122:16)
```

**Comment by calebdwilliams** [comment]
This is fixed in `element-internals-polyfill@1.1.12`.
